name: WeatherTimePlaceholder
version: '1.0.0-SNAPSHOT'
main: pl.ktmc.weatherTimePlaceholder.WeatherTimePlaceholder
api-version: '1.21'
softdepend: [ PlaceholderAPI ]
description: 'PlaceholderAPI expansion for weather and time placeholders.'
